apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PMA_HOST
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: pma_host
            - name: PMA_PORT
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: pma_port
            - name: PMA_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: pma_user
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: pma_password
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
