# `kubectl create ns database`
# `kubectl apply -f q11.yaml`
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: database
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:oraclelinux9
        ports:
        - containerPort: 80
        env:
          - name: MYSQL_DATABASE
            valueFrom: 
              configMapKeyRef:
                name: db-configmap
                key: MYSQL_DATABASE
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MYSQL_PASSWORD
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MYSQL_USER
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
  namespace: database
data:
  MYSQL_DATABASE: "db"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: database
data:
  MYSQL_ROOT_PASSWORD: MTIzNDVteXNxbAo=
  MYSQL_PASSWORD: MTIzbXlzcWwK
  MYSQL_USER: bXlzcWwK
