# `kubectl create ns qq3`
# `kubectl apply -f q3.yaml`
# `kubectl set image deployment/nginx-deployment nginx=nginx:latest -n qq3`
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: qq3
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

