# `kubectl create ns prod`
# `kubectl apply -f q7.yaml`
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01
  namespace: prod
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app01-svc
  namespace: prod
spec:
  type: NodePort
  selector:
    app: 
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80

