# `kubectl create ns qq2`
# `kubectl apply -f q11.yaml`
---
apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: qq2
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: "/data" 
      name: pv
      readOnly: true
  volumes:
    - name: pv
      persistentVolumeClaim:
        claimName: pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: qq2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
