# `kubectl create ns qq3`
# `kubectl apply -f q15.yaml`
# `kubectl set image deployment apache-deployment apache=httpd:bookworm -n qq3`
# `kubectl rollout undo deployment apache-deployment -n qq3`
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: qq3
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:latest
        ports:
        - containerPort: 80

