# `kubectl create ns qq3`
# `kubectl apply -f q5.yaml`
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: limit
  namespace: qq3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 80
          name: web
