# `kubectl create ns prod`
# `kubectl apply -f q7.yaml`
# `kubectl get endpoints`
# `curl <endpoint-ip>:30000`
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01
  namespace: prod
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: app01-svc
  namespace: prod
spec:
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPorto: http-web-svc
    nodePort: 30000
  type: LoadBalancer
