apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  MARIADB_ROOT_PASSWORD: MTIzcm9vdA== # 123root
  PMA_USER: cm9vdA== # root
  PMA_PASSWORD: MTIzcm9vdA== # 123root
  WORDPRESS_DB_USER: d29yZHByZXNz # wordpress
  WORDPRESS_DB_PASSWORD: MTIzd29yZHByZXNz # 123wordpress
  WORDPRESS_DB_NAME: d29yZHByZXNz # wordpress