apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  namespace: programming
  labels:
    app: python
spec:
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: python:latest
        ports:
        - containerPort: 9797

