apiVersion: apps/v1
kind: Deployment
metadata:
  name: class
  labels:
    app: class
spec:
  replicas: 3
  selector:
    matchLabels:
      app: class
  template:
    metadata:
      labels:
        app: class
    spec:
      containers:
      - name: nginx
        image: nginx:alpine3.20
        ports:
        - containerPort: 80
          name: http-port
        - containerPort: 443
          name: https-port

