apiVersion: v1
kind: Pod
metadata:
  name: stuck-pod
  namespace: default
spec:
  containers:
    - name: nginx
      image: nginx:latest
  nodeSelector:
    disktype: ssd #changed to disktype: ssd and label the node with disktype: ssd
