apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: pvc
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123mysql"
        - name: MYSQL_DATABASE
          value: "test"
        - name: MYSQL_USER
          value: "admin"
        - name: MYSQL_PASSWORD
          value: "123admin"
        volumeMounts:
        - name: mysql-pv
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-pv
        persistentVolumeClaim:
          claimName: mysql-pvc
