apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: pvc
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin:latest
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123mysql"
        - name: PMA_HOST
          value: mysql-svc
