apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - database
              topologyKey: "kubernetes.io/minikube"
      containers:
      - name: frontend
        image: ariwesi/timesheet_angular:v1
        ports:
        - containerPort: 4200
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "frontendandbackend"
        effect: "NoSchedule"