# kubectl autoscale deployment autoscale-app --cpu-percent=65 --min=3 --max=15
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscale-app
spec:
  selector:
    matchLabels:
      app: autoscale-app
  template:
    metadata:
      labels:
        app: autoscale-app
    spec:
      containers:
      - name: autoscale-app
        image: httpd:2.4
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: autoscale-service
  labels:
    app: autoscale-service
spec:
  ports:
  - port: 80
  selector:
    app: autoscale-app
