apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-job
spec:
  schedule: "* */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-job
            image: alpine:latest
            command:
            - /bin/sh
            - -c
            - tar -czf /backup/data.tar.gz /data
          restartPolicy: OnFailure
