apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
data:
  api_key: TVlfU0VDUkVUX0tFWV8xMjM0Cg==
  api_token: U3VwZXJTZWN1cmVUb2tlbjk4NzYK
---
apiVersion: v1
kind: Pod
metadata:
  name: api-client
spec:
  containers:
  - name: api-client
    image: python:3.8
    ports:
    - containerPort: 80
    volumeMounts:
      - name: secret-volume
        mountPath: "/etc/secrets"
  volumes:
    - name: secret-volume
      secret:
        secretName: api-credentials