apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: database
  labels:
    app: db-service
spec:
  ports:
  - port: 80
    name: db-service
  clusterIP: None
  selector:
    app: db-cluster
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-cluster
  namespace: database
spec:
  serviceName: "db-service"
  replicas: 3
  selector:
    matchLabels:
      app: db-cluster
  template:
    metadata:
      labels:
        app: db-cluster
    spec:
      containers:
      - name: db-cluster
        image: mysql:8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123mysql"
  volumeClaimTemplates:
  - metadata:
      name: db-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi

