apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: test
  labels: 
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
      name: nginx-web